name: Release
on: [workflow_dispatch]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
    steps:

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2.1.4

    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Run semantic-release
      run: npx -p @semantic-release/changelog -p semantic-release@17.3.0 -p @semantic-release/git semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to github registry
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:{{ .Version }}
          ghcr.io/${{ github.repository }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
          ghcr.io/${{ github.repository }}:{{ .Major }}.{{ .Minor }}
          ghcr.io/${{ github.repository }}:{{ .Major }}
