name: Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
